[package]
name = "zone2021"
version = "0.1.0"
authors = ["katsuNakajima <40666782+katsuNakajima@users.noreply.github.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]

[profile.release]
lto = true
panic = 'abort'
